name: CI/CD to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm ci

    - name: Copy files to EC2 (rsync)
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -avzr --delete
        path: ./
        remote_path: /home/ubuntu/my-app/releases/temp
        remote_host: ${{ secrets.EC2_HOST }}
        remote_user: ${{ secrets.EC2_USER }}
        remote_key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy on server (symlink + PM2)
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          set -e
          TIMESTAMP=$(date +%Y%m%d%H%M)
          RELEASE_DIR="/home/ubuntu/my-app/releases/$TIMESTAMP"

          mkdir -p $RELEASE_DIR
          rsync -av --delete /home/ubuntu/my-app/releases/temp/ $RELEASE_DIR/
          rm -rf /var/www/my-app/releases/temp

          ln -sfn $RELEASE_DIR /home/ubuntu/my-app/current

          cd /home/ubuntu/my-app/releases/temp
          npm ci --omit=dev

          pm2 stop my-app || true
          pm2 start index.js --name my-app
          pm2 save
